### ISSUE TITLE
Bosch Controller 2 in Iobroker

### ISSUE THREAD

**Issue by Matzeonom** [holomekc/ioBroker.bshb#205]
I think, this issue matches that group better and still hope for some idea - getting crazy....

https://github.com/BoschSmartHome/bosch-shc-api-docs/issues/71#issue-1553515002

Thanks in advance, regards to all

**Comment by holomekc** [comment]
Hi @Matzeonom 
Some issues so far:
1. I do not know if the controller 2 has the same local api.
2. I do not know if the controller 2 has a local api at all.
3. Local api documentation is offline for some time: BoschSmartHome/bosch-shc-api-docs#70

The only way to figure this out (and test it), would be to buy the device and again do crazy things to figure out the protocol. I am currently not willing to do so, because already controller 1 took me ages with zero benefit. 

I will take a look when I have some time. Maybe I am missing something. I do not really think that they changed everything. That would be quite a lot of effort to update their app. But maybe they changed something in the authentication process.

Br
Chris

**Comment by holomekc** [comment]
Hi @Matzeonom
Another thing. Maybe you can post some logs from iobroker of the pairing process. Best would be with log level debug. Then maybe I can see more. Maybe they only replaced the SSL certificate. That would be an easy fix then. Do not forget to remove personal information like the password which is logged in the http request.

**Comment by Matzeonom** [comment]
Hi @holomekc ,
thank you for joining the discussion. 
I really hoped, that there is more experience here already and from other users with Ver2 of the Controller.

I am not in technical detail, but (or especially because of the that) highly appreciate your effort with Controller 1.

My experience with controller 2 so far: connection-barcodes not really readable with the mobile, worser connection (2 amplifier needed where none was before)...it only can get better !

However: here the logging during pairing-process attached herewith

Thanks to you (and others) in advance
Matze

PS: I have another Controller2 available - if you like...´;-)

[Iobroker.txt](https://github.com/holomekc/ioBroker.bshb/files/10502498/Iobroker.txt)

**Comment by holomekc** [comment]
Hi @Matzeonom,
thx can you now do the following. Call the following url in your browser (I hope you use Chrome. Otherwise, I need to check how to get access to it. Or you can look for a guide for your browser how to get the server certificate):
https://{yourControllerIp}:8443/

It will look like this:
![image](https://user-images.githubusercontent.com/30546982/214660305-4e10ab1f-61fc-4158-9676-2c402cb8ca23.png)

Then click on the "Not secure" in my picture "Nicht sicher" 
![image](https://user-images.githubusercontent.com/30546982/214661152-c6a50ca4-58ae-421f-afce-81726616d64f.png)

Then click on "Certificate is invalid" or something like this. In the picture "Zertifikat ist ungültig". Then you get something like this:
![image](https://user-images.githubusercontent.com/30546982/214662391-9d467c9e-6249-472d-a273-3a4b2bbf5d08.png)

Then click on details and select the first entry (yellow one):
![image](https://user-images.githubusercontent.com/30546982/214662924-a570a1c4-bef9-40a1-8500-2b705036e89c.png)

click on export. It should preselect the crt export format. This is ok. Then you can send it to me or you can send it to me or you can check if it ends with: ...NfaO6SAFz8

![image](https://user-images.githubusercontent.com/30546982/214664311-322aeaa0-822d-4f82-b70d-b8f8dcf217d0.png)

**Comment by Matzeonom** [comment]
I hope, I did everything right - end of the certificate differs from the above.
What now ?

**Comment by holomekc** [comment]
Then I need this information to update the application. The adapter refuses to connect to the controller, because it does not understand the server certificate and thinks that it is not a valid device. The other option would be to make the connection more insecure so that something like MITM attacks would be possible. Which is more theoretically because of local connection anyway. But yeah. We could try it if you are willing to do so. I would update the adapter in GitHub and when you would install it from here you could test if the change then works.

**Comment by sebastianharder** [comment]
Hey @holomekc, 
the API is the same for the new SHC II. But, indeed, the certificate might have changed.
Also, to pair, the user needs to press the button on the device only shortly, instead of 3 s.
That confused already some users of HomeAssistant.

Regards,
Sebastian

**Comment by Matzeonom** [comment]
@holomekc : This is, what is noted in my log-file (at the end): 
WMxnZ+67w=
-----END CERTIFICATE-----
@sebastianharder: Thanks for clarification: it noticed, that a "short press" results in 2 LED blinking, long press: only one...
Not sure, what is right - now I am !

With a lot of luck, we get this issue sorted out soon - I (and hopefully others) will be happy...

Thanks so far

**Comment by holomekc** [comment]
Hi. I need the complete public certificate of the Bosch root ca. No worry about this thing. It is the same for all c2 devices. You can see that the c1 certificate is also in code:

https://github.com/holomekc/bosch-smart-home-bridge/blob/master/src/bshb-utils.ts

Br,
Chris

**Comment by Matzeonom** [comment]
Honestly, I have no clue, what I am gonna post here - any information to calm me down...sorry for being such a rookie...

**Comment by holomekc** [comment]
Hi @Matzeonom,
no problem. I try to explain it without too much detail. I hope ;). 

A certificate is used by a server so that clients can verify its authenticity. This is part to make the connection to this server secure. So for a secure connection every server needs such a certificate.

So the next question for a client is, does it trust the server. You can image it would be very difficult to store certificates of all devices. So in our case every Bosch Controller has its own certificate. So difficult for clients to know all of them. 

Therefore these certificates are created by certificate authorities. These authorities also have certificates. There are not that many so way easier for clients to know them. So in our case we want the certificate of the Bosch Root certificate authority (CA). There is just one (I hope) used for all Bosch Controller certificates.

When you check the picture I posted above you see three entries in the List (Chain). The lowest one is the certificate of your device. This is unique per device, so we do not want this. The second is a so called intermediate cert better but also not needed. The one at the top is the root ca. This we want.
 
When I install this in the adapter, the adapter trusts all Bosch Controller 2 certificates.

Due to powerful math ;) the certificate in this case is no private information. You can open any webpage and check all certificates from root, intermediate and the server cert.

I hope it was not too technical. As said you can check the link above where the root ca cert of controller 1 is stored in the bosch lib code. I would do the same with the one of controller 2. 

You said you have two Controller 2 devices. In theory you could check both and the root certificate of both should be the same.

**Comment by holomekc** [comment]
Hi @Matzeonom 

I pushed a new update to GitHub. It allows to disable the certificate check:
![image](https://user-images.githubusercontent.com/30546982/215221328-52f50cb3-d530-4dbe-9ff3-735c71978c0d.png)

As mentioned it is less secure, but you should be able to test the connection to controller 2 with this.

**Comment by Matzeonom** [comment]
Hi @holomekc,
thanks for your effort so far - am a bit busy today, but will look into your last 2 posts this evening and will come back to you than.
Enjoy the weekend !
Matze

**Comment by Matzeonom** [comment]
Hi @holomekc,

if have sent you an email, how to proceed. 
The above as a bit beyont my knowledge/possibilities...

In any case - happy to see so many supportive people here - thanks.
Matze
