### ISSUE TITLE
Error 500 when trying to trigger OutdoorSiren alarm via ioBroker

### ISSUE THREAD

**Issue by BenS89** [holomekc/ioBroker.bshb#253]
**Describe the bug**  
I installed the Bosch OutdoorSiren and added it into the Bosch App. Now I want to trigger the alarm via `bshb.0.hdm:ZigBee:003c84fffeexxxxxx.OutdoorSiren.acousticAlarmOn`

**Expected behavior**  
The alarm gets triggered

**Actual behavior**  
The following error is shown in the log:

`Error: Could not send update for "deviceHandler" with path=/devices/hdm:ZigBee:003c84fffeebxxxxx/services/OutdoorSiren. [cause] BshbError: [ERROR] call to BSHC failed with HTTP status=500`

How can I enable and disable the alarming so that I can expose this later on in HomeKit?

Thanks and best regards
Ben

**Comment by holomekc** [comment]
Hi. I cannot really help here. I do not own this device. I do not see much in the docu: https://local.apidocs.bosch-smarthome.com/

Normally what I do in this situations. Use the offical Bosch App and execute the action you want to do there. Meanwhile you can check the ioBroker Adapter and check what values changed, and which values the different objects have during the action.

You can also monitor the updates object in the root directory of the adapter. All updates are shown there. 

The 500 Error is the normal behaivor, when the Controller does not like that you try to change a value, which cannot be changed. 

The issue is I also do not know all the values and which are editable and which are not. I tried to cover most of the devices I own, but I tried to give the people all the feedom with their devices so that they are normally able to figure the values out by themselves. But I am happy to collect some feedback regarding the different values the OutdorSiren has. Then I can update some values. See:
https://github.com/holomekc/ioBroker.bshb/tree/master/src/definition

**Comment by BenS89** [comment]
Hmm, seems like Bosch restricts security related assessories from being triggered by local API:
https://community.bosch-smarthome.com/t5/kompatibilität-von-fremdprodukten/bosch-smart-home-außensirene-und-apple-homekit/m-p/37197
