### ISSUE TITLE
Change Arm-Profile

### ISSUE THREAD

**Issue by MrDrache333** [holomekc/ioBroker.bshb#36]
I can arm or disarm the Security System via Node-RED, but if I want to change the Mode from Full-Protection to Half-Protection there is no passible way to do so? Ive tried to set the current activeProfile first from 0 to 1 and then ARM the System but that didn't work. Is there any possible way to do so?

Very nice Adapter btw 😉

**Comment by holomekc** [comment]
Hi. Thanks it makes me happy that you like the adapter.
I am not sure why it is not working yet. Maybe the controller expects that both values are set at the same time which is currently not possible via the adapter because the values are handled separately. I need to do some testing. If it is the case I need to cache the profile value and always send it when the arming state is changed. 

I do not really like that because currently the adapter is kind of „stupid“ because it does not really know the values but follows the pattern of controller messages. And this would be a new pattern. I will take a look this weekend if I find the time.

**Comment by MrDrache333** [comment]
Thanks for the fast answer. That would be nice, if the activeProfile would be read out when the System was set to Arm via ioBroker. 

If you want me to share a Yahka configuration with the Help of node-red i've managed to fully integrate the Security System into HomeKit with every function, please let me know.

Thanks for your Work. 👍🏻

**Comment by holomekc** [comment]
Hi would be great. Just create a new issue with the wiki content as markdown. I will then update the wiki.

**Comment by sebastianharder** [comment]
The new API 2.1 supports the profiles, see BoschSmartHome/bosch-shc-api-docs/blob/master/CHANGELOG.md#210---2021-01-22

**Comment by holomekc** [comment]
Profiles will be supported in version 0.1.13:
https://github.com/holomekc/ioBroker.bshb/issues/37
