### ISSUE TITLE
Pairing not possible

### ISSUE THREAD

**Issue by MSpecht87** [holomekc/ioBroker.bshb#42]
when i try to pair the adapter i get error code 6 back. please find error Log attached.

[ErrorLog.txt](https://github.com/holomekc/ioBroker.bshb/files/6385240/ErrorLog.txt)

**Comment by holomekc** [comment]
Hi. As mentioned in the logs. Did you press the pairing button? If so you can also increase the log level. Debug or silly. Then you can see the HTTP messages in detail. 

So far it looks like that the controller refuses during SSL handshake. This normally happens when you do not have a suitable certificate, which is the case when the adapter is not paired.

Without getting into technical details. Only when the controller is in pairing mode it allows registration of new clients. So what you can do is:

1. Restart adapter
2. Press pairing mode button on Bosch Controller for around 3s so that it starts blinking. Then you should see that the adapter will connect.

**Comment by MSpecht87** [comment]
Hello, Thanks for you quick response. unfortunatly I already tried the two options you mentioned serveral times. I even changed the password to make sure there are no unknowen characters in it. I will try to increase the log level hopfully I will get more detailed informations. 

do you have an idea what this error means:
2021-04-27 16:03:17.670 - error: host.raspberrypi-ioBroker instance system.adapter.bshb.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

kind regards

**Comment by holomekc** [comment]
Hmm I guess this is still some not that nice error handling from my side. I guess I still have the situation that although controller was in pairing mode and therefore the SSL handshake worked fine the response of the controller was not expected so that pairing could not be completed. See log before:

```2021-04-27 14:09:38.943 - info: bshb.0 (2238) Unexpected pairing response. Most likely wrong input data. Check password, etc. Pairing stopped.```

I would recommend to enable "silly" logging in iobroker for the adapter. Then you can see HTTP request/response to/from controller. I am not sure how far your  knowledge goes but it should contain some readble text and status code like 401 or 403. You can send me the details if you cannot see an issue. But make sure to remove private information if you do not want to share them.

**Comment by MSpecht87** [comment]
I've now turned up the log level and found a few errors. Among other things, as you already suspected, unauthorized status 401. Unfortunately, I don't understand the reason for this. I've attached part of the log.
[Log.txt](https://github.com/holomekc/ioBroker.bshb/files/6394423/Log.txt)

**Comment by holomekc** [comment]
Hi. 401 = Unauthorized. This means that your password is wrong. You can try again or you can check in the silly logs (search for "Systempassword") if the password you configured is the correct one. The password is base64 encoded with a proper tool you can decode it and check if you have a typo in it.

**Comment by MSpecht87** [comment]
Hello, so when I translate the password from log I found an unkwonen(wrong translated) typo in it. I was a little confused that it worked with my other diveces from Bosch. How ever now it works with another password. Thank you very much for you support
